# en raíz dbt_project.yml
name: 'my_new_project'
version: '1.0.0'
config-version: 2
profile: 'default'

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analyses"]
test-paths: ["tests"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  my_new_project:
    +materialized: view
    +on_schema_change: append_new_columns

    b_bronze:
      +schema: BRONZE
      +materialized: table

    c_silver:
      +schema: SILVER
      +materialized: table

    d_gold:
      +schema: GOLD
      +materialized: table

    staging:
      +schema: STAGING
      +materialized: view

seeds:
  +schema: BRONZE
  +quote_columns: true
